package domain

import "errors"

var (
	ErrPhoneNotFound            = errors.New("phone not found")
	ErrPhoneAlreadyExists       = errors.New("phone already exists")
	ErrAccountAlreadyExists     = errors.New("account already exists")
	ErrPhoneInactive            = errors.New("phone inactive")
	ErrInvalidPin               = errors.New("invalid pin")
	ErrInvalidInput             = errors.New("invalid input")
	ErrUserNotFound             = errors.New("user not found")
	ErrInvalidLogin             = errors.New("invalid login")
	ErrInvalidPassword          = errors.New("invalid password")
	ErrUserInactive             = errors.New("user inactive")
	ErrClientAlreadyExists      = errors.New("client already exists")
	ErrClientInactiveExists     = errors.New("client inactive exists")
	ErrClientNotFound           = errors.New("client not found")
	ErrClientInactive           = errors.New("client inactive")
	ErrPhoneAlreadyUsed         = errors.New("phone already used")
	ErrAccountNotFound          = errors.New("account not found")
	ErrAccountInactive          = errors.New("account inactive")
	ErrIdentificationFailed     = errors.New("identification failed")
	ErrAccountNotIdentified     = errors.New("account not identified")
	ErrInsufficientFunds        = errors.New("insufficient funds")
	ErrInvalidAmount            = errors.New("invalid amount")
	ErrSameAccountTransfer      = errors.New("same account transfer")
	ErrTransactionFailed        = errors.New("transaction failed")
	ErrConcurrentBalanceChanged = errors.New("concurrent balance changed")
)
